import type { Metadata } from "next";
import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import cx from "classnames";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cx(
          "h-full w-full bg-primary-100 p-2 md:p-4 lg:p-6 text-secondary max-h-screen",
          urbanist.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
